// <auto-generated />
using System;
using MVC_Core_DbFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_Core_DbFirst.Migrations
{
    [DbContext(typeof(LpuDbContext))]
    [Migration("20260309051847_Initial Create")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_Core_DbFirst.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__Person__3214EC07ED972CA7");

                    b.ToTable("Person", "PankajBatch");
                });

            modelBuilder.Entity("MVC_Core_DbFirst.Models.Product", b =>
                {
                    b.Property<int>("ProdId")
                        .HasColumnType("int")
                        .HasColumnName("ProdID");

                    b.Property<string>("Category")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProdId")
                        .HasName("PK__Products__042785C5A577B5DE");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MVC_Core_DbFirst.Models.StudentInfo", b =>
                {
                    b.Property<int>("RollNo")
                        .HasColumnType("int");

                    b.Property<short>("Age")
                        .HasColumnType("smallint");

                    b.Property<string>("LocalAddr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("PerAddr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SchoolName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Air Force School");

                    b.HasKey("RollNo")
                        .HasName("PK__StudentI__7886D5A0C840120B");

                    b.ToTable("StudentInfo", (string)null);
                });

            modelBuilder.Entity("MVC_Core_DbFirst.Models.StudentMark", b =>
                {
                    b.Property<int>("Chem")
                        .HasColumnType("int");

                    b.Property<int>("Maths")
                        .HasColumnType("int");

                    b.Property<int?>("Perc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("((([Physics]+[Chem])+[Maths])/(3))", false);

                    b.Property<int>("Physics")
                        .HasColumnType("int");

                    b.Property<int?>("RollNo")
                        .HasColumnType("int");

                    b.Property<int>("SrNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("srNo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SrNo"));

                    b.Property<int?>("TotalMarks")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("(([Physics]+[Chem])+[Maths])", false);

                    b.HasIndex("RollNo");

                    b.ToTable("StudentMarks");
                });

            modelBuilder.Entity("MVC_Core_DbFirst.Models.StudentMark", b =>
                {
                    b.HasOne("MVC_Core_DbFirst.Models.StudentInfo", "RollNoNavigation")
                        .WithMany()
                        .HasForeignKey("RollNo")
                        .HasConstraintName("FK__StudentMa__RollN__68487DD7");

                    b.Navigation("RollNoNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
